@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTk2Nzc2MDMsInVzZXJfaWQiOjF9.SBkS4v1u5thJ8gvbiXmfs-ZjZYM8_7TPBd82MLBmjWE

###
POST /api/auth/login HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "login": "ra_1",
  "password": "ra"
}
###

###
POST /api/auth/refresh HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "user_id": 1,
  "refresh_token": "11a987ff0ee34786645401cc1886d5ae2515f7602a95c143ebae0587e5023f91"
}
###

###
POST /api/auth/logout HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "user_id": 1
}
###

###
GET /api/books HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer {{access_token}}
###

###
GET /api/books?search=А HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer {{access_token}}
###

###
GET /api/books/1 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer {{access_token}}
###

###
POST /api/books HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "book_name": "Новая книга",
  "book_total_quantity": 50,
  "book_pages_amount": 200,
  "book_desc": "Описание книги",
  "book_price": 500.0,
  "book_cover": true,
  "book_super_cover": true,
  "book_publisher": "Издательство",
  "book_year_release": 2025,
  "book_isbn": "0-000-0000-0"
}
###

###
PUT /api/books/2 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "book_name": "Новая книга",
  "book_total_quantity": 50,
  "book_pages_amount": 200,
  "book_desc": "Описание книги",
  "book_price": 500.0,
  "book_cover": true,
  "book_super_cover": true,
  "book_publisher": "Издательство",
  "book_year_release": 2025,
  "book_isbn": "0-000-0000-0"
}
###

###
DELETE /api/books/1 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer {{access_token}}
###
