@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjAyNzg3MDAsInVzZXJfaWQiOjF9.AYsWkxjl79vw7epZb89BMDNwchR_VsDSwy8p2uGSkHI

###
POST /api/auth/login HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "login": "ra_1",
  "password": "ra"
}
###

###
POST /api/auth/refresh HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "user_id": 1,
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjAyNzg2MDYsInVzZXJfaWQiOjF9.Hum-5isFPpss5pzCYFnvi13NEeWGoYkoD7lxbPHYdmg1"
}
###

###
POST /api/auth/logout HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "user_id": 1
}
###

###
GET /api/books HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer {{access_token}}
###

###
GET /api/books?search=А HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer {{access_token}}
###

###
GET /api/books/1 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer {{access_token}}
###

###
POST /api/books HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "book_name": "Новая книга",
  "book_total_quantity": 50,
  "book_pages_amount": 200,
  "book_desc": "Описание книги",
  "book_price": 500.0,
  "book_cover": true,
  "book_super_cover": true,
  "book_publisher": "Издательство",
  "book_year_release": 2025,
  "book_isbn": "0-000-0000-0"
}
###

###
PUT /api/books/2 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "book_name": "Новая книга",
  "book_total_quantity": 50,
  "book_pages_amount": 200,
  "book_desc": "Описание книги",
  "book_price": 500.0,
  "book_cover": true,
  "book_super_cover": true,
  "book_publisher": "Издательство",
  "book_year_release": 2025,
  "book_isbn": "0-000-0000-0"
}
###

###
DELETE /api/books/1 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer {{access_token}}
###
